[package]
name = "miner"
version = "0.1.0"
authors = ["modderme123 <modderme123@gmail.com>"]

[dependencies]
piston_window = "0.75"

rand = "0.4"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"